import type { ShipModule } from './types';

export const MODULES: ShipModule[] = [
  {
    id: 'arcaneum',
    name: 'Arcaneum',
    cost: 1000,
    description: 'Room carved with stabilizing runes and magical devices for arcane research and studying magical objects.',
    functionName: 'Ritual Tools',
    functionDescription: 'Cast any known/prepared ritual-tagged spell as a ritual, even without usual ritual casting ability.',
    prerequisite: 'The ability to cast at least one spell',
    improvements: [
      { id: 'component-gel', name: 'Component Gel', cost: 2500, description: 'Material cost of spells of 5th level or lower cast here are halved.' },
      { id: 'arcane-amplifier', name: 'Arcane Amplifier', cost: 4000, description: 'Damage spells cast here deal an extra 1d6 force damage.' },
    ],
    maxQuantity: 1,
    category: 'utility',
  },
  {
    id: 'armory',
    name: 'Armory',
    cost: 500,
    description: 'Lockers for weapons and armor, with decorative displays and optional training space.',
    functionName: 'Basic Arsenal',
    functionDescription: 'Includes one of every simple and martial weapon. Must be returned/replaced before taken again.',
    improvements: [
      { id: 'endless-quiver', name: 'Endless Quiver', cost: 1500, description: 'Produces unlimited nonmagical ammunition for stored ranged weapons.' },
      { id: 'training-grounds', name: 'Training Grounds', cost: 2000, description: 'Creatures that long rest here gain temporary HP equal to their level.' },
    ],
    category: 'crew',
  },
  {
    id: 'automaton-bay',
    name: 'Automaton Bay',
    cost: 3500,
    description: 'Four cylindrical pods housing automatons connected to the spelljamming helm.',
    functionName: 'Deploy Sentinels',
    functionDescription: 'Mobilize four clockwork sentinels (animated armor stats). Captain chooses lethal or non-lethal.',
    improvements: [
      { id: 'gradual-repairs', name: 'Gradual Repairs', cost: 1500, description: 'Sentinels regain 1 HP at end of each day in their pods.' },
      { id: 'personal-wards', name: 'Personal Wards', cost: 1000, description: 'After a day in pods, sentinels gain temporary HP equal to half their max.' },
      { id: 'elite-sentinels', name: 'Elite Sentinels', cost: 5000, description: 'Upgrade one sentinel to helmed horror stats. Choose three Spell Immunity spells.', repeatable: true },
    ],
    maxQuantity: 1,
    category: 'combat',
  },
  {
    id: 'cargo-hold',
    name: 'Cargo Hold',
    cost: 500,
    description: 'Open space for trade goods and supplies. Each one increases cargo limit by 5 tons.',
    functionName: 'Bay Door',
    functionDescription: 'As an action, pull a lever to open a bay door on the wall or floor.',
    improvements: [
      { id: 'ship-dock', name: 'Ship Dock', cost: 500, description: 'The space is outfitted to hold any one vehicle that can completely fit inside it. Opening the bay door ejects the vehicle out of the ship and into the nearest unoccupied space large enough to hold it.' },
      { id: 'void-lock', name: 'Void Lock', cost: 250, description: "The bay door can't be opened while in space, unless a special command word is spoken as the lever is pulled (the command word can be chosen and changed using the spelljamming helm)." },
    ],
    category: 'utility',
  },
  {
    id: 'cryogenic-ward',
    name: 'Cryogenic Ward',
    cost: 4000,
    description: 'Eight glass tubes for suspended animation with vital sign monitoring.',
    functionName: 'Astral Sleep',
    functionDescription: 'Suspended animation: unaware, no aging, no needs, immune to psychic damage, poisons/diseases paused.',
    improvements: [
      { id: 'emergency-revival', name: 'Emergency Revival', cost: 2000, description: 'Tubes auto-revive occupants on critical ship damage.' },
      { id: 'healing-stasis', name: 'Healing Stasis', cost: 3000, description: 'Creatures in tubes regain 1 HP per day.' },
    ],
    maxQuantity: 1,
    category: 'utility',
  },
  {
    id: 'dormitories',
    name: 'Dormitories',
    cost: 500,
    description: 'Sleeping quarters for up to four crew members with bunks and footlockers.',
    functionName: 'Crew Logs',
    functionDescription: 'Command word-protected magical tablet for documenting time aboard.',
    improvements: [
      { id: 'deluxe', name: 'Deluxe', cost: 100, description: 'If every dormitory has this, overall crew morale improves.' },
      { id: 'window', name: 'Window', cost: 100, description: 'Space-safe magical glass lets occupants see into space.' },
    ],
    category: 'crew',
  },
  {
    id: 'drone-center',
    name: 'Drone Center',
    cost: 1000,
    description: 'Scrying surfaces, controls, and airlock housing a remote-controlled clockwork drone.',
    functionName: 'Remote Drone',
    functionDescription: 'Drone senses magic within 30 ft. (detect magic) and manipulates objects under 10 lbs.',
    improvements: [
      { id: 'energetic-paneling', name: 'Energetic Paneling', cost: 800, description: 'Drone is resistant to cold, fire, and lightning damage.' },
      { id: 'self-destruct', name: 'Self-Destruct', cost: 500, description: 'Drone self-destructs: DC 14 Dex save or 14 (4d6) fire within 10 ft.' },
    ],
    maxQuantity: 1,
    category: 'utility',
  },
  {
    id: 'escape-pod',
    name: 'Escape Pod',
    cost: 800,
    description: 'Detachable pod seating up to four, flung at 60 ft./round in a random direction.',
    functionName: 'Emergency Evacuation',
    functionDescription: 'Up to 4 creatures deploy the pod. Survives crash-landing. Deploying destroys the docking bay.',
    improvements: [
      { id: 'distress-beacon', name: 'Distress Beacon', cost: 1000, description: 'Deployed pods emit a distress signal detectable up to 100 million miles.' },
      { id: 'cryo-stasis', name: 'Cryo-Stasis', cost: 5000, description: 'Deployed pod plunges occupants into cryogenic sleep until forced open.' },
    ],
    category: 'crew',
  },
  {
    id: 'grasper',
    name: 'Grasper',
    cost: 2500,
    description: 'A long grasping limb (tentacle, claw, pincer) to manipulate objects outside the ship.',
    functionName: 'Manipulate Grasper',
    functionDescription: 'As an action, use the limb to grab something outside the ship. Reach: 20 feet.',
    improvements: [
      { id: 'greater-reach', name: 'Greater Reach', cost: 800, description: 'Limb reach increases to 30 feet.' },
      { id: 'crushing-force', name: 'Crushing Force', cost: 1000, description: 'Attack bonus +5, deals 16 (2d10+5) bludgeoning on hit.' },
    ],
    category: 'combat',
  },
  {
    id: 'greenhouse',
    name: 'Greenhouse',
    cost: 1200,
    description: 'Natural space with magical sunlight for growing plants in space.',
    functionName: 'Grow Plants',
    functionDescription: 'Each work week: Food (1d8 x 10 lbs.), Medicine (1d8 x 25 gp herbs), or Poison (1d8 x 25 gp).',
    prerequisite: 'Proficiency in Nature or Survival',
    improvements: [
      { id: 'enriched-soil', name: 'Enriched Soil', cost: 2000, description: "The yield of the Greenhouse's Grow Plants function is doubled." },
      { id: 'alchemists-station', name: "Alchemist's Station", cost: 200, description: "The Greenhouse functions as a set of alchemist's supplies, an herbalism kit, and a set of poisoner's tools." },
    ],
    category: 'utility',
  },
  {
    id: 'intelligence-core',
    name: 'Intelligence Core',
    cost: 5000,
    description: 'A sentient magical intelligence that sees, hears, and speaks from any room. Accesses all modules.',
    functionName: 'Artificial Crew Member',
    functionDescription: 'Captain assigns core to any unfilled role. Downloads proficiencies and operates modules via helm.',
    improvements: [
      { id: 'enhanced-personality', name: 'Enhanced Personality', cost: 2000, description: 'Develops more complex personality for nuanced conversation.' },
      { id: 'tactical-analysis', name: 'Tactical Analysis', cost: 3000, description: 'Advantage on one Intelligence check per day related to ship combat.' },
    ],
    maxQuantity: 1,
    category: 'special',
  },
  {
    id: 'landing-legs',
    name: 'Landing Legs',
    cost: 1000,
    description: 'Four or more legs allowing the ship to land without rolling over.',
    functionName: 'Safe Landing',
    functionDescription: 'Ship can land on ground without rolling over, regardless of keel and beam size.',
    improvements: [
      { id: 'fall-stabilizer', name: 'Fall Stabilizer', cost: 1000, description: 'Falling damage from crash-landing is halved.' },
      { id: 'walking-legs', name: 'Walking Legs', cost: 1000, description: 'While on ground, ship has walking speed of 30 ft.' },
    ],
    maxQuantity: 1,
    category: 'utility',
  },
  {
    id: 'lounge',
    name: 'Lounge',
    cost: 500,
    description: 'Sofas, dining table, chairs, and viewing port. Multipurpose recreation space.',
    functionName: 'Crew Recreation',
    functionDescription: 'Comfortable space for relaxation and socialization, improving morale.',
    improvements: [
      { id: 'mess-hall', name: 'Mess Hall', cost: 300, description: 'Full kitchen for proper crew meals.' },
      { id: 'entertainment', name: 'Entertainment', cost: 500, description: 'Games, instruments, and diversions significantly improve morale.' },
    ],
    category: 'crew',
  },
  {
    id: 'medical-bay',
    name: 'Medical Bay',
    cost: 1200,
    description: 'Examination table, medical supplies, and vital sign machines.',
    functionName: 'Medical Treatment',
    functionDescription: 'Medicine-proficient creature treats one poison/disease/condition over a day; target gets advantage on further saves.',
    prerequisite: 'Proficiency in Medicine',
    improvements: [
      { id: 'poison-lab', name: 'Poison Lab', cost: 800, description: 'Create 1d4 antitoxin vials over 8 hours (potency lost after 24h).' },
      { id: 'creature-lab', name: 'Creature Lab', cost: 800, description: 'Study creature body part over 8 hours to learn resistances/immunities/vulnerabilities.' },
      { id: 'medical-archives', name: 'Medical Archives', cost: 500, description: 'Research checks for poisons, diseases, and conditions have advantage.' },
    ],
    maxQuantity: 1,
    category: 'utility',
  },
  {
    id: 'plane-gate',
    name: 'Plane Gate',
    cost: 8000,
    description: 'Arcane circle of runes and crystal nodes for interplanar travel.',
    functionName: 'Interplanar Travel',
    functionDescription: 'Spellcaster transports ship to random location on another plane. One exhaustion level. Once per 24 hours.',
    prerequisite: 'The ability to cast at least one spell',
    improvements: [
      { id: 'safety-regulators', name: 'Safety Regulators', cost: 1000, description: 'Exhaustion only on failed DC 15 Constitution save.' },
      { id: 'precision-gate', name: 'Precision Gate', cost: 4000, description: 'Declare a specific location; ship appears within 1d4\u00d7100 miles.' },
    ],
    maxQuantity: 1,
    category: 'special',
  },
  {
    id: 'ram',
    name: 'Ram',
    cost: 1500,
    description: 'A sturdy ram on the front: huge fist, spear, dragon head, or other form.',
    functionName: 'Ram Attack',
    functionDescription: '+8 to hit, reach 0 ft. Hit: 88 (16d10) bludgeoning/piercing/slashing. Ship takes half and stops.',
    improvements: [],
    maxQuantity: 1,
    category: 'combat',
  },
  {
    id: 'spelljamming-helm',
    name: 'Spelljamming Helm',
    cost: 5000,
    description: 'The mandatory module containing the spelljamming helm to propel the ship.',
    functionName: 'Steering the Ship',
    functionDescription: 'A spelljammer moves and steers the ship without expending their own actions or movement.',
    improvements: [
      { id: 'protective-barrier-helm', name: 'Protective Barrier', cost: 800, description: 'While at the helm, a creature has half cover in all directions.' },
      { id: 'escape-pod-helm', name: 'Escape Pod', cost: 500, description: 'If the ship is destroyed, the helm ejects as an Escape Pod module.' },
    ],
    maxQuantity: 1,
    category: 'core',
  },
  {
    id: 'terrarium',
    name: 'Terrarium',
    cost: 1500,
    description: 'Open room mimicking natural terrain for housing a wild animal or alien creature.',
    functionName: 'Animal Housing',
    functionDescription: 'Suitable environment with adjustable biome conditions.',
    improvements: [
      { id: 'high-security-hold', name: 'High-Security Hold', cost: 1000, description: 'Reinforced for dangerous creatures. Resistant to inner damage. DC 25 Strength to break door.' },
      { id: 'comfort-sensor', name: 'Comfort Sensor', cost: 500, description: 'Auto-senses and matches optimal conditions for any placed animal.' },
    ],
    category: 'utility',
  },
  {
    id: 'treant',
    name: 'Treant',
    cost: 5000,
    description: 'Weaves a willing treant into the deck. Only at construction. Top deck only.',
    functionName: 'Living Hull',
    functionDescription: 'Treant (speed 0) takes actions. On long rest: repairs 4d12 HP and refreshes air envelope.',
    improvements: [
      { id: 'protective-barrier-treant', name: 'Protective Barrier', cost: 800, description: 'Protective wood shell grants the treant half cover.' },
    ],
    maxQuantity: 1,
    category: 'special',
  },
  {
    id: 'ward-generator',
    name: 'Ward Generator',
    cost: 2000,
    description: 'This room contains a huge metal device with an array of hex crystals in its core. By passing power through this room and into the hull, the device throws a protective field of magic around the ship, absorbing damage that would otherwise damage it. With a Ward Generator installed, the ship\'s damage threshold increases to 20.',
    functionName: 'Localized Shield',
    functionDescription: 'Once per round, as a reaction, you can subtract the ship\'s damage threshold from the triggering damage roll.',
    improvements: [
      { id: 'specialized-shields', name: 'Specialized Shields', cost: 2000, description: 'Choose one damage type: acid, cold, fire, lightning, or thunder. Unless the ward generator is damaged, the ship has resistance to the chosen damage type. You can change the damage type by taking this improvement again for 500 gp.', repeatable: true },
      { id: 'heightened-shields', name: 'Heightened Shields', cost: 4000, description: 'The Localized Shield function subtracts double the ship\'s damage threshold from the triggering damage.' },
    ],
    maxQuantity: 1,
    category: 'combat',
  },
  {
    id: 'weapon-bay',
    name: 'Weapon Bay',
    cost: 500,
    description: 'Hosts a shipboard weapon. Choose up to two Ballistae or Mangonels. Cost = 500 gp + weapon costs.',
    functionName: 'Operate Weapons',
    functionDescription: 'A creature in the Weapon Bay can operate installed weapons with easy access to ammunition.',
    improvements: [
      { id: 'protective-barrier-wb', name: 'Protective Barrier', cost: 800, description: 'A creature in the Weapon Bay has half cover.' },
      { id: 'stabilizer', name: 'Stabilizer', cost: 1000, description: 'Weapon normal range is doubled, long range unchanged.' },
      { id: 'self-mending-weapon', name: 'Self-Mending', cost: 2500, description: 'At end of each day below half HP max, the weapon regains 1 HP.' },
    ],
    category: 'combat',
  },
];

export function getModuleById(id: string): ShipModule | undefined {
  return MODULES.find(m => m.id === id);
}
