import type { WeaponType, WeaponBayImprovement } from './types';

export const WEAPON_TYPES: WeaponType[] = [
  {
    id: 'ballista',
    name: 'Ballista',
    cost: 50,
    ac: 15,
    hp: 50,
    crew: 3,
    actionsToLoad: 1,
    actionsToAim: 1,
    actionsToFire: 1,
    attackName: 'Bolt',
    attackBonus: 6,
    normalRange: 120,
    longRange: 480,
    damage: '3d10',
    damageType: 'piercing',
  },
  {
    id: 'mangonel',
    name: 'Mangonel',
    cost: 100,
    ac: 15,
    hp: 100,
    crew: 5,
    actionsToLoad: 2,
    actionsToAim: 2,
    actionsToFire: 1,
    attackName: 'Mangonel Stone',
    attackBonus: 5,
    normalRange: 200,
    longRange: 800,
    damage: '5d10',
    damageType: 'bludgeoning',
  },
  {
    id: 'cannon',
    name: 'Cannon',
    cost: 0,
    ac: 15,
    hp: 75,
    crew: 3,
    actionsToLoad: 1,
    actionsToAim: 1,
    actionsToFire: 1,
    attackName: 'Cannonball',
    attackBonus: 6,
    normalRange: 120,
    longRange: 480,
    damage: '8d10',
    damageType: 'bludgeoning',
  },
  {
    id: 'starlight-cannon',
    name: 'Starlight Cannon',
    cost: 500,
    ac: 17,
    hp: 100,
    crew: 4,
    actionsToLoad: 2,
    actionsToAim: 1,
    actionsToFire: 1,
    attackName: 'Star Sphere',
    attackBonus: 6,
    normalRange: 150,
    longRange: 600,
    damage: '4d10',
    damageType: 'radiant',
  },
];

export const WEAPON_BAY_IMPROVEMENTS: WeaponBayImprovement[] = [
  {
    id: 'protective-barrier',
    name: 'Protective Barrier',
    cost: 800,
    description: 'A creature standing in the Weapon Bay has half cover.',
  },
  {
    id: 'stabilizer',
    name: 'Stabilizer',
    cost: 1000,
    description: 'Weapon normal range is doubled, but long range remains the same.',
  },
  {
    id: 'self-mending-weapon',
    name: 'Self-Mending',
    cost: 2500,
    description: 'At the end of each day where the weapon is below half its HP max, the weapon regains 1 HP. Cannot repair at 0 HP.',
  },
];
